version: '3'
services:
    nginx:
        image: nginx:1.13
        container_name: "niche-nginx"
        environment:
            - APP_DIR
        ports:
            - 80:80
        links:
            - "php-fpm:php.host"
        volumes:
            - "${APP_DIR}:/niche:rw"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - php-fpm
            - mysql
#        logging:
#            driver: "syslog"
#            options:
#                syslog-facility: "local0"
#                tag: "niche-nginx"

    php-fpm:
        build: ./docker/php
        container_name: "niche-php"
        links:
            - "mysql:mysql.host"
        entrypoint: /bin/bash /tmp/entrypoint.sh
        working_dir: /niche
        volumes:
            - "${APP_DIR}:/niche:rw"
            - "./docker/php/entrypoint.sh:/tmp/entrypoint.sh"
#        logging:
#            driver: "syslog"
#            options:
#                syslog-facility: "local0"
#                tag: "niche-php"

    mysql:
        image: mysql:5.6
        container_name: "niche-mysql"
        environment:
            - MYSQL_DATA_DIR
            - MYSQL_ROOT_PASSWORD
        ports:
            - 127.0.0.1:3306:3306
        volumes:
            - "${MYSQL_DATA_DIR}:/var/lib/mysql"
#        logging:
#            driver: "syslog"
#            options:
#                syslog-facility: "local0"
#                tag: "niche-mysql"
